name: Run Training a job in AML

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string
      # compute:
      #   description: 'Azure Machine Learning compute cluster name'
      #   required: true
      #   default: 'dev-vm-cluster' 
      #   type: amlcluster

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: check a path
      run: pwd && ls
    - name: Run Training a job using aml cluster
      run: 
        az ml job -h
        # az ml job -f /home/runner/work/aml-github-actions/aml-github-actions/src/job.yml -g rg-dev-mlops - w mlw-dev-mlops
       